# Generated by Django 4.1.1 on 2023-05-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depressedMood', models.IntegerField()),
                ('feelingsOfGuilt', models.IntegerField()),
                ('suicide', models.IntegerField()),
                ('initialInsomnia', models.IntegerField()),
                ('insomniaDuringTheNight', models.IntegerField()),
                ('delayedInsomnia', models.IntegerField()),
                ('workAndInterests', models.IntegerField()),
                ('retardation', models.IntegerField()),
                ('agitation', models.IntegerField()),
                ('psychiatricAnxiety', models.IntegerField()),
                ('somaticAnxiety', models.IntegerField()),
                ('gastrointestinalSomaticSymptoms', models.IntegerField()),
                ('generalSomaticSymptoms', models.IntegerField()),
                ('hypochondriasis', models.IntegerField()),
                ('weightLoss', models.IntegerField()),
                ('insight', models.IntegerField()),
            ],
        ),
    ]
